### ISSUE TITLE
 When Spring Context is refreshed/recreated some Cron Tasks configurations are duplicated in the strongbox-cron-tasks.yaml file 

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1299]
# Task Description

Some cron tasks are created during the server startup (for example [DownloadRemoteFeedCronJob](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/cron/jobs/DownloadRemoteFeedCronJob.java)) (see also [NugetRepositoryManagementStrategy](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/repository/NugetRepositoryManagementStrategy.java)) and then saved in the `strongbox-cron-tasks.yaml` file. We should check and validate the existence of the same configuration, because on server restart, these entries are duplicated in the  `strongbox-cron-tasks.yaml` file.

Currently we have following cron jobs created during server startup:
* [ ] `DownloadRemoteFeedCronJob` 
* [ ] `FetchRemoteNpmChangesFeedCronJob`
* [ ] `RebuildMavenIndexesCronJob` 
* [ ] `DownloadRemoteMavenIndexCronJob`

We need to stop duplicating the same jobs in the `strongbox-cron-tasks.yaml` file.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@ptirador ,

Would this be something you'd like to look into?

**Comment by ptirador** [comment]
@fuss86 @carlspring Let's assume that a new cron task is created, and it has a different UUID but the same job class as a task in the yaml file. Should we assume that this new cron task is in fact a duplicate, and we should skip it and don't add it to the file?

**Comment by carlspring** [comment]
Hi @ptirador ,

Yes, you should, because you can have cron tasks for different repositories. For example, you can have a cron task that removes all the snapshots from a snapshot repository for all artifacts tha have been released. So, this could be set up per repository. OBviously, these different configurations will be using the same class, but will have different names.

**Comment by ptirador** [comment]
Great, thanks!

**Comment by ptirador** [comment]
@carlspring @fuss86 : Hi! I still have doubts with the cron tasks duplicates in the yaml file.
So, just to be clear, let's suppose we have this yaml file:

```
  - uuid: "4485a5ab-d785-4043-9ca7-e584a98a8faa"
    name: "Config 1"
    jobClass: "org.carlspring.strongbox.cron.jobs.FetchRemoteNpmChangesFeedCronJob"
    cronExpression: "0 0 * ? * * *"
    oneTimeExecution: false
    immediateExecution: true
    properties:
      repositoryId: "npmjs"
      storageId: "storage-npm"
- uuid: "5485a5ab-d785-4043-9ca7-e584a98a8faa"
    name: "Config 1"
    jobClass: "org.carlspring.strongbox.cron.jobs.FetchRemoteNpmChangesFeedCronJob"
    cronExpression: "0 0 * ? * * *"
    oneTimeExecution: false
    immediateExecution: true
    properties:
      repositoryId: "npmjs"
      storageId: "storage-npm"
  - uuid: "6485a5ab-d785-4043-9ca7-e584a98a8faa"
    name: "Config 2"
    jobClass: "org.carlspring.strongbox.cron.jobs.FetchRemoteNpmChangesFeedCronJob"
    cronExpression: "0 0 * ? * * *"
    oneTimeExecution: false
    immediateExecution: true
    properties:
      repositoryId: "npmjs"
      storageId: "storage-npm"
```

Are the 2nd and the 3rd element duplicates of the first one?
The second is exactly the same except for the UUID.
The third element is the same except for the UUID and name.
