### ISSUE TITLE
Test the LDAP Authorization 

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1614]
# Task Description
Strongbox have configurable authentication which can be setup with `strongbox-authentication-providers.yaml`. By default, only users who are stored in the database can be authorized. Additionally authorization can be configured through an external LDAP server as shown below:
```
strongbox:
  authentication:
    strongboxUserDetailService:
      order: 1
      enabled: true
    ldapUserDetailsService:
      order: 0
      enabled: true
    passwordAuthenticationProvider:
      order: 0
      enabled: true
    jwtAuthenticationProvider:
      order: 1
      enabled: true
    securityTokenAuthenticationProvider:
      order: 2
      enabled: true
    ldap:
      url: ldap://gw.vm:389/dc=carlspring,dc=com
      managerDn: cn=Admin,dc=carlspring,dc=com
      managerPassword: 1234
      rolesMapping:
        - externalRole: strongbox
          strongboxRole: ADMIN
        - externalRole: Contributors
          strongboxRole: USER_ROLE
      userDnPatterns:
        - uid={0},ou=Users,dc=carlspring,dc=com
      groupSearchBase: ou=Groups,dc=carlspring,dc=com
      groupSearchFilter: (uid={0})
      authorities:
        groupSearchBase: ou=Groups
        groupSearchFilter: (uniqueMember={0})
        convertToUpperCase: false
        groupRoleAttribute: ou
        rolePrefix: ''
        searchSubtree: true
```
Within this task we need to check how this configuration actually works with Strongbox distribution.
# Tasks

The following tasks will need to be carried out:
* [x] Check that LDAP configuration applied for Strongbox instance 
* [x] Check that LDAP users can be authenticated in Strongbox
* [x] Check that configured role mappings works for LDAP users
* [x] Provide the documentation of how to configure LDAP authentication

# Task Relationships

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
