### ISSUE TITLE
Make it possible to use standalone cassandra

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1790]
# Task Description

We need to allow usage of standalone Cassandra instances for cases where you'd like to run a cluster of Cassandra instances.
There should be an environment variable called `STRONGBOX_REMOTE_CASSANDRA` and a `strongbox.yaml` configuration variable which would need to be an array of strings as shown in JG's docs ([storage.hostname](https://docs.janusgraph.org/basics/configuration-reference/#storage))

`strongbox.yaml`: 
```yaml
strongbox: 
  configuration:
    database:
      # If true -> starts embedded cassandra; 
      # if false -> passes the string array below to JG
      embedded: true|false
      # This term comes from datastax's driver and refers to the coordinator node you will be connecting to
      # If embedded:true, this option should be optional and should default to 127.0.0.1:9042
      contactPoints: [ "1.2.3.4:9042", "2.3.4.5:9042" ]
      authentication: (optional, if missing assume `username=null` and `password=`null`)
        username: "my-cassandra-user" (if blank, `username=null`)
        password: "my-cassandra-password" (if blank, `password=null`)
```

Maybe we could have a `janusgraph:` section here which directly maps values to `JanusGraphFactory.build().set(key,val)` as well, but if it's too much work we can add a follow-up 

`STRONGBOX_REMOTE_CASSANDRA`:
* `STRONGBOX_REMOTE_CASSANDRA=1.2.3.4:9042,2.3.4.5:9042` should be translated as `contactPoints: [1.2.3.4:9042, 2.3.4.5:9042]`
* `STRONGBOX_REMOTE_CASSANDRA_USER=username` -> `authentication.username=username` 
* `STRONGBOX_REMOTE_CASSANDRA_PASS=password` -> `authentication.password=password`

# Task Relationships

This task:
* Is a sub-task of: #1649

**Comment by sbespalov** [comment]
we already have the `strongbox.db.janus-graph.profile` which cold be one of the following:
```
-Dstrongbox.db.janus-graph.profile=janusgraph_MEMORY
-Dstrongbox.db.janus-graph.profile=janusgraph_EMBEDDED
-Dstrongbox.db.janus-graph.profile=janusgraph_REMOTE
```
within this task I would implement the `janusgraph_REMOTE`

**Comment by sbespalov** [comment]
this probably will be better to rename the property to `strongbox.db.profile`

**Comment by steve-todorov** [comment]
I agree renaming the property to keep consistency. Will the env vars work as well?

**Comment by sbespalov** [comment]
regarding the backend cluster they assume that all storage hosts should have same port, so probably it won't be possible to have different ports within hosts
the configuration should be like follows:
```
storage.hostname=1.2.3.4, 2.3.4.5, 3.4.5.6
storage.port=49142
```

**Comment by sbespalov** [comment]
regarding the configuration the purpose is to have `db_<strongbox.db.profile>.yaml` file under `etc/conf` folder. This configuration file will have profile dependent configuration properties like below (`db_REMOTE.yaml` configuration example for cassandra cluster):
```
strongbox:
    db:
        janus-graph:
            storage-username: cassandra
            storage-password: cassandra
            storage-host: 1.2.3.4, 2.3.4.5, 3.4.5.6
            storage-port = 49142
```
The appropriate configuration file will be picked up based on `-Dstrongbox.db.profile` or `STRONGBOX_JANUSGRAPH_PROFILE` value.
