### ISSUE TITLE
Fix `strongbox-security-users.yaml`

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1981]
# Bug Description

Within application startup the `strongbox-security-users.yaml` file is overwritten with the wrong format. The problem is that `users.user.roles` collection contains objects instead of strings which is expected by `UserDto`

# Steps To Reproduce

1. Run distribution with `./bin/strongbox console`
2. Startup process failed with following exception:
```
21:38:48.431 | E | main       | o.s.boot.SpringApplication            | Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.carlspring.strongbox.config.UsersConfig': Invocation of init method failed; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (BufferedInputStream); line: 8, column: 7] (through reference chain: org.carlspring.strongbox.users.dto.UsersDto["user"]->java.util.LinkedHashSet[0]->org.carlspring.strongbox.users.dto.UserDto["roles"]->java.util.LinkedHashSet[0])

```
# Task Relationships

This bug:
* Relates to:  #1676, #1985

**Comment by steve-todorov** [comment]
Thanks for fixing this issue @sbespalov! :)

I tried this and it works. 

However there is another issue which is that the initial `strongbox-security-users.yaml` file is still being overwritten at runtime. 
I haven't looked into the "how", but to me this is yet another bug which we should fix (outside of the JG migration), because it can lead to harmful data loss (i.e. when you comment out portion of the yaml with the idea to come back to it later)

I noticed this is happening somewhere around the StorageBooter by doing `watch -n 1 -- cat etc/conf/strongbox-security-users.yaml`. Do you know which parts of the code might be responsible for this issue and are points of interest? 
We should create a ticket for later and put it on hold. 

Original `strongbox-security-users.yaml` file packaged with the `tar.gz`:
```yaml
users:
  user:
    - username: admin
      password: "redacted(non-changed)"
      roles:
        - ADMIN
      securityTokenKey: redacted(non-changed)
    - username: deployer
      password: "redacted(non-changed)"
      roles:
        - UI_MANAGER
        - ARTIFACTS_MANAGER
      securityTokenKey: deployer-secret
    # testing 2
    - username: deployer2
      password: "redacted(non-changed)"
      roles:
        - UI_MANAGER
        - ARTIFACTS_MANAGER
      securityTokenKey: redacted(non-changed)

```

File after `./bin/strongbox console` is started

```yaml
---
users:
  user:
  - username: "admin"
    password: "redacted(non-changed)"
    enabled: true
    securityTokenKey: "redacted(non-changed)"
    roles:
    - "ADMIN"
  - username: "deployer"
    password: "redacted(non-changed)"
    enabled: true
    securityTokenKey: "redacted(non-changed)"
    roles:
    - "ARTIFACTS_MANAGER"
    - "UI_MANAGER"
  - username: "deployer2"
    password: "redacted(non-changed)"
    enabled: true
    securityTokenKey: "redacted(non-changed)"
    roles:
    - "ARTIFACTS_MANAGER"
    - "UI_MANAGER"
```
