### ISSUE TITLE
The strongbox-security-users config file is overwritten at runtime

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1985]
# Bug Description

The initial `strongbox-security-users.yaml` file is being overwritten at runtime. 

I haven't looked into the "how", but this can lead to harmful data loss (i.e. when you comment out portion of the yaml with the idea to come back to it later).

I noticed this is happening somewhere around the `StorageBooter` stage while watching for changes to the file via `watch -n 1 -- cat etc/conf/strongbox-security-users.yaml`.

Original `strongbox-security-users.yaml` file packaged with the `tar.gz`:
```yaml
users:
  user:
    - username: admin
      password: "redacted(non-changed)"
      roles:
        - ADMIN
      securityTokenKey: redacted(non-changed)
    - username: deployer
      password: "redacted(non-changed)"
      roles:
        - UI_MANAGER
        - ARTIFACTS_MANAGER
      securityTokenKey: deployer-secret
    # I've added this before the first start for testing purposes and to see if the comment is deleted.
    #- username: deployer2
    #  password: "redacted(non-changed)"
    #  roles:
    #    - UI_MANAGER
    #    - ARTIFACTS_MANAGER
    #  securityTokenKey: redacted(non-changed)

```

File after `./bin/strongbox console` is started

```yaml
---
users:
  user:
  - username: "admin"
    password: "redacted(non-changed)"
    enabled: true
    securityTokenKey: "redacted(non-changed)"
    roles:
    - "ADMIN"
  - username: "deployer"
    password: "redacted(non-changed)"
    enabled: true
    securityTokenKey: "redacted(non-changed)"
    roles:
    - "ARTIFACTS_MANAGER"
    - "UI_MANAGER"
```

# Steps To Reproduce

1. `git clone https://github.com/strongbox/strongbox.git`
2. `git checkout issues/1649`
3. `mvn clean install -DskipTests`
4. `cd strongbox-distribution/target`
5. `tar xzf *.tar.gz && cd strongbox-distribution-*/strongbox-*-SNAPSHOT/`
6. `./bin/strongbox console`
7. in another terminal watch the `strongbox-security-users.yaml` file for changes (i.e. `watch -n 1 -- cat etc/conf/strongbox-security-users.yaml`)

# Expected Behavior

The file shouldn't change at all - this should be the responsibility of the user and shouldn't be happening automatically since it can lead to data loss.

# Environment

* Strongbox Version: branch `issues/1649` (and most likely `master`)

# Tasks

* [ ] Investigate why this is happening and pin point the problematic code
* [ ] Fix
* [ ] Submit a PR :)
* [ ] Might be worth checking if other configuration files are being overwritten at runtime as well and if so - make an additional task which links to this one.

# Task Relationships

This bug:
* Relates to: Was noticed in #1981, but has been introduced at some time earlier.
